# Generated by Django 5.1 on 2024-08-16 23:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="post",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AddField(
            model_name="post",
            name="modified_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
