# Generated by Django 5.1 on 2024-08-20 23:01

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0002_alter_post_options_post_modified_at"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name="post",
            old_name="title",
            new_name="movie_name",
        ),
        migrations.RenameField(
            model_name="post",
            old_name="content",
            new_name="my_review",
        ),
        migrations.AddField(
            model_name="post",
            name="duration",
            field=models.CharField(default="00h00", max_length=10),
        ),
        migrations.AddField(
            model_name="post",
            name="gif",
            field=models.ImageField(blank=True, null=True, upload_to="post/%Y/%m"),
        ),
        migrations.AddField(
            model_name="post",
            name="synopsis",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="post",
            name="year",
            field=models.IntegerField(
                default=1900,
                validators=[django.core.validators.MinValueValidator(1900)],
            ),
        ),
        migrations.AddField(
            model_name="reaction",
            name="author",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reactions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
