# Generated by Django 5.1 on 2024-08-20 23:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0003_rename_title_post_movie_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="gif_url",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="post",
            name="image_url",
            field=models.TextField(blank=True),
        ),
    ]
