# Generated by Django 5.1 on 2024-08-21 04:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0004_post_gif_url_post_image_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="reaction",
            name="post",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reactions",
                to="blog.post",
            ),
        ),
    ]
