# Generated by Django 5.1 on 2024-08-21 21:28

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0005_reaction_post"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MoviePost",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("movie_name", models.CharField(max_length=100)),
                ("synopsis", models.TextField(blank=True)),
                ("my_review", models.TextField(blank=True)),
                (
                    "year",
                    models.IntegerField(
                        default=1900,
                        validators=[django.core.validators.MinValueValidator(1900)],
                    ),
                ),
                ("duration", models.CharField(default="00h00", max_length=10)),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="post/image/%Y/%m"
                    ),
                ),
                (
                    "gif",
                    models.ImageField(
                        blank=True, null=True, upload_to="post/gif/%Y/%m"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="posts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="posts",
                        to="blog.category",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AlterField(
            model_name="reaction",
            name="post",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reactions",
                to="blog.moviepost",
            ),
        ),
        migrations.DeleteModel(
            name="Post",
        ),
    ]
