# Generated by Django 5.1 on 2024-08-22 00:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0006_moviepost_alter_reaction_post_delete_post"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="reaction",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AddField(
            model_name="comment",
            name="post",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="blog.moviepost",
            ),
        ),
    ]
